import { beforeAll, describe, expect, it } from 'vitest';
import { extractFromSource } from '../src/extraction/tree-sitter';
import { loadGrammarsForLanguages } from '../src/extraction/grammars';
import { scanMacroContribution } from '../src/extraction/macro-scan';
import { selectUnambiguousCppMacroDefinitions } from '../src/extraction/declaration-macros';
import { CCppSourceScope } from '../src/extraction/c-cpp-source-scope';

beforeAll(async () => { await loadGrammarsForLanguages(['c', 'cpp']); });

function cpp(source: string, file = 'neutral.hpp') {
  const context = scanMacroContribution(source);
  return extractFromSource(file, source, 'cpp', undefined,
    new Set(context.names), new Set(context.bodyless), selectUnambiguousCppMacroDefinitions(context.definitions));
}

describe('C/C++ declaration evidence', () => {
  it('does not turn a declaration macro without a source semicolon into a field', () => {
    const nodes = cpp(`#define DECL_METHOD(name) int name(int value);
class Gauge { public:
  DECL_METHOD(run)
  static const char label[];
};`).nodes;
    expect(nodes.filter(n => n.name === 'DECL_METHOD').map(n => n.kind)).toEqual(['macro']);
    expect(nodes).toContainEqual(expect.objectContaining({kind:'method', name:'run'}));
    expect(nodes).toContainEqual(expect.objectContaining({kind:'field', name:'label'}));
  });

  it('distinguishes a decltype base class from an elaborated function return type', () => {
    const source = 'struct Child : decltype(factory()) { static int member; };\nstruct Child make() { int local = 0; return {}; }';
    const scope = new CCppSourceScope(source);
    expect(scope.isExecutable(source.indexOf('member'))).toBe(false);
    expect(scope.isExecutable(source.indexOf('local'))).toBe(true);
    expect(cpp(source).nodes).toContainEqual(expect.objectContaining({kind:'field', name:'member'}));
    expect(cpp(source).nodes.some(n => n.name === 'local')).toBe(false);
  });

  it.each(['REPORT_VALUE', 'describe_fields'])('keeps expanded methods, not the %s invocation wrapper', macro => {
    const source = `#define ${macro}(arg) int report() const { return 1; }
struct Gauge {
  ${macro}(value);
  int value;
};`;
    const nodes = cpp(source).nodes;
    expect(nodes).toContainEqual(expect.objectContaining({kind:'method', name:'report', qualifiedName:'Gauge::report'}));
    expect(nodes.filter(n => n.name === macro).map(n => n.kind)).toEqual(['macro']);
    expect(nodes).toContainEqual(expect.objectContaining({kind:'field', name:'value'}));
  });

  it('keeps copy constructors and assignment generated by a declaration macro', () => {
    const nodes = cpp(`#define NO_COPY(T) T(const T&); void operator=(const T&)
class Widget { NO_COPY(Widget); };`).nodes;
    expect(nodes).toContainEqual(expect.objectContaining({kind:'method', name:'Widget', isDeclaration:true}));
    expect(nodes).toContainEqual(expect.objectContaining({kind:'method', name:'operator=', isDeclaration:true}));
    expect(nodes.some(n => n.kind === 'method' && n.name === 'NO_COPY')).toBe(false);
  });

  it('keeps typed functions and constructors sharing a macro name', () => {
    const nodes = cpp(`#define SHARED(x) impl(x)
#define Widget(x) impl(x)
#undef SHARED
#undef Widget
int SHARED(int x) { return x; }
struct Widget { Widget(); ~Widget(); operator bool() const; };`).nodes;
    expect(nodes).toContainEqual(expect.objectContaining({kind:'function', name:'SHARED'}));
    for (const name of ['Widget', '~Widget', 'operator bool']) {
      expect(nodes).toContainEqual(expect.objectContaining({kind:'method', name}));
    }
  });

  it.each(['fragment.hpp', 'fragment.ipp'])('does not turn assignments in %s into declarations', file => {
    const result = cpp('case 1: output = 10; break;\ncase 2: output += 20; break;', file);
    expect(result.nodes.filter(n => ['variable','constant'].includes(n.kind))).toEqual([]);
  });

  it('requires adjacent broken type evidence while preserving global declaration recovery', () => {
    const result = extractFromSource('globals.c', `EXPORT_ATTR WORD_TYPE counter = 42;
EXPORT_ATTR WORD_TYPE *pointer = 0;
int global_after = 3;`, 'c');
    for (const name of ['counter', 'pointer', 'global_after']) {
      expect(result.nodes).toContainEqual(expect.objectContaining({kind:'variable', name}));
    }
    expect(result.nodes.some(n => n.name === 'WORD_TYPE')).toBe(false);
  });

  it('keeps a function body after another declaration on the same expanded line', () => {
    const source = `#define MAKE_TEST(owner, name) class owner##_##name { public: void body(); }; void owner##_##name::body()
MAKE_TEST(Probe, Works)
{
  int local_counter = 1;
}
int after;`;
    const result = cpp(source);
    expect(result.nodes.filter(n => n.name === 'body')).toEqual([
      expect.objectContaining({kind:'method', qualifiedName:'Probe_Works::body', startLine:2, endLine:5}),
    ]);
    expect(result.nodes.find(n => n.name === 'body')?.isDeclaration).not.toBe(true);
    expect(result.nodes.some(n => n.kind === 'function' && n.name === 'MAKE_TEST')).toBe(false);
    expect(result.nodes.some(n => n.name === 'local_counter')).toBe(false);
    const method = result.nodes.find(n => n.name === 'body')!;
    expect(method.startColumn).toBeLessThan(source.split('\n')[1]!.length);
  });

  it('isolates statement macros in one recovered body from the next generated class', () => {
    const nodes = cpp(`#define MAKE(owner) class owner { public: void body(); }; void owner::body()
MAKE(First)
{
  CHECK_TOKEN(int, "value", ->);
  CHECK_TOKEN(void, 12, ::);
}
MAKE(Second)
{
  int hidden;
}`).nodes;
    for (const name of ['First', 'Second']) {
      expect(nodes).toContainEqual(expect.objectContaining({kind:'class', name}));
      const method = nodes.find(n => n.kind === 'method' && n.qualifiedName === name+'::body');
      expect(method).toBeDefined();
      expect(method?.isDeclaration).not.toBe(true);
      expect(method?.endLine).toBe(name === 'First' ? 6 : 10);
    }
    expect(nodes.some(n => n.name === 'hidden')).toBe(false);
  });

  it('keeps the closing boundary of a generated function longer than 512 lines', () => {
    const nodes = cpp('#define CASE(owner) class owner { public: void body(); }; void owner::body()\n'
      + 'CASE(LongCase)\n{\n' + '  touch();\n'.repeat(600) + '}\nCASE(AfterCase)\n{\n}\n').nodes;
    expect(nodes).toContainEqual(expect.objectContaining({kind:'class', name:'AfterCase'}));
    const first = nodes.find(n => n.kind === 'method' && n.qualifiedName === 'LongCase::body');
    expect(first?.endLine).toBe(604);
    expect(first?.isDeclaration).not.toBe(true);
    expect(nodes).toContainEqual(expect.objectContaining({kind:'method', qualifiedName:'AfterCase::body',endLine:607}));
  });

  it('preserves types on an expanded invocation line and ignores raw-string brace payloads', () => {
    const nodes = cpp(`#define WITH_TYPE(owner) int owner() { struct Generated { int member; }; return 0; }
#define CASE(owner) class owner { public: void body(); }; void owner::body()
WITH_TYPE(factory)
CASE(First)
{
  const char *text = R"tag( " { }
  } " { )tag";
}
CASE(Second)
{
}
`).nodes;
    expect(nodes).toContainEqual(expect.objectContaining({kind:'struct', name:'Generated'}));
    expect(nodes).toContainEqual(expect.objectContaining({kind:'class', name:'Second'}));
    expect(nodes.some(n => n.name === 'text')).toBe(false);
  });

  it('keeps later namespace types when separate macros provide a function opening and close', () => {
    const result = cpp(`#define BEGIN(name) void name() { int internal_value = 0;
#define END }
#define DEFINE_TYPE(name) namespace { struct name { static const char label[]; }; } const char name::label[] = "type"; const char *const reg_##name = name::label;
BEGIN(setup)
  use();
END
namespace outer {
  DEFINE_TYPE(Descriptor)
}
`);
    const type = result.nodes.find(n => n.kind === 'struct' && n.qualifiedName === 'outer::Descriptor');
    expect(type).toBeDefined();
    expect(result.nodes).toContainEqual(expect.objectContaining({kind:'constant', qualifiedName:'outer::Descriptor::label'}));
    expect(result.nodes).toContainEqual(expect.objectContaining({kind:'constant', qualifiedName:'outer::reg_Descriptor'}));
    const parent = result.nodes.find(n => n.kind === 'namespace' && n.name === 'outer');
    expect(result.edges).toContainEqual(expect.objectContaining({kind:'contains',source:parent?.id,target:type?.id}));
    expect(result.nodes.some(n => n.name === 'internal_value')).toBe(false);
  });

  it('keeps a following source body when a namespace expansion ends with a function header', () => {
    const nodes = cpp(`#define WITH_HEADER(name) namespace { struct Marker {}; } void name()
WITH_HEADER(run)
{
  int local_value;
}
`).nodes;
    expect(nodes).toContainEqual(expect.objectContaining({kind:'function',name:'run',startLine:2,endLine:5}));
    expect(nodes.find(n => n.name === 'run')?.isDeclaration).not.toBe(true);
    expect(nodes.some(n => n.name === 'local_value')).toBe(false);
  });

  it('removes definition comments before alias substitution without erasing literal URLs', () => {
    const nodes = cpp(`#define ALIAS target // a definition comment
#define URL "https://example.test" // not part of the string
#define REGISTER(name) namespace { struct name { int field; }; } const int *const ptr_##name = &ALIAS; const char *const url_##name = URL;
int target;
REGISTER(Descriptor)
`).nodes;
    expect(nodes).toContainEqual(expect.objectContaining({kind:'struct', name:'Descriptor'}));
    expect(nodes).toContainEqual(expect.objectContaining({kind:'constant', name:'ptr_Descriptor'}));
    expect(nodes).toContainEqual(expect.objectContaining({kind:'constant', name:'url_Descriptor',signature:expect.stringContaining('https://example.test')}));
  });

  it('does not expand the alphabetic suffix of a preprocessing number', () => {
    const nodes = cpp(`#define suffix struct Unwanted {};
#define HEX unexpected
#define INNER(name) namespace { struct Type_##name { int member; }; } int value_##name;
#define OUTER(name) INNER(name)
OUTER(123suffix)
OUTER(0xHEX)
constexpr auto literal = 123suffix;
`).nodes;
    for (const name of ['Type_123suffix','Type_0xHEX']) {
      expect(nodes).toContainEqual(expect.objectContaining({kind:'struct', name}));
    }
    expect(nodes.some(n => n.name === 'Unwanted' || n.name.includes('unexpected'))).toBe(false);
  });

  it('keeps macro-generated qualified definitions with a trailing semicolon as methods', () => {
    const nodes = cpp(`#define IMPL(owner) int owner::front() { return back(); }; int owner::back()
namespace sample {
IMPL(Worker)
{
  return 1;
}
}`).nodes;
    for (const name of ['front', 'back']) {
      const method = nodes.find(n => n.kind === 'method' && n.qualifiedName === 'sample::Worker::'+name);
      expect(method).toBeDefined();
      expect(method?.isDeclaration).not.toBe(true);
    }
  });

  it('preserves the class child of a damaged declaration with unresolved constructor macros', () => {
    const nodes = cpp(`namespace sample {
class Widget : public Base {
  UNKNOWN_CTOR(Widget), value(0) { ; }
  UNKNOWN_COPY(Widget, delete)
  UNKNOWN_DTOR(Widget) { ; }
};
}`).nodes;
    expect(nodes).toContainEqual(expect.objectContaining({kind:'class', name:'Widget', qualifiedName:'sample::Widget'}));
  });

  it('rejects call expressions and constructor initializers as recovered definitions', () => {
    const nodes = cpp(`namespace audit { bool ready(); }
void inspect(int flag) {
  if (flag &&
      !audit::ready()) {}
}
struct Device { bool enabled; Device() :
  enabled(audit::ready()) {}
};
@`).nodes;
    expect(nodes.filter(n => n.name === 'ready')).toEqual([
      expect.objectContaining({kind:'function', qualifiedName:'audit::ready', isDeclaration:true}),
    ]);
    expect(nodes).toContainEqual(expect.objectContaining({kind:'method', name:'Device'}));
  });

  it('preserves qualified static-member definitions, arrays, pointers and templates', () => {
    const nodes = cpp(`namespace sample {
struct Item { static const char label[]; static int *ptr; };
const char Item::label[] = "item";
int *sample::Item::ptr = nullptr;
template<class T> struct Box { static int count; };
template<class T> int Box<T>::count = 1;
}
int sample::Item::other = 2;`).nodes;
    for (const qualifiedName of ['sample::Item::label','sample::Item::ptr','sample::Box<T>::count','sample::Item::other']) {
      expect(nodes).toContainEqual(expect.objectContaining({qualifiedName}));
    }
    expect(nodes.some(n => ['sample::label','sample::ptr','sample::sample::Item::ptr'].includes(n.qualifiedName))).toBe(false);
  });

  it('does not borrow a masked statement terminator to invent macro-named variables', () => {
    const nodes = cpp(`#define BEGIN_INPUTS(name) void inputs_##name() {
#define ADD_BIT(v) sink.bit(v);
#define EIGHT_WAY sink.way(8);
#define FOR_PLAYER(n) sink.player(n);
#define END_INPUTS }
BEGIN_INPUTS(demo)
  ADD_BIT(1) EIGHT_WAY FOR_PLAYER(1)
  ADD_BIT(2) EIGHT_WAY FOR_PLAYER(2)
END_INPUTS
struct Value {};
#undef FOR_PLAYER
Value FOR_PLAYER(1);`).nodes;
    expect(nodes.filter(n => n.kind === 'variable' && n.name === 'FOR_PLAYER')).toEqual([
      expect.objectContaining({startLine:12}),
    ]);
  });
});

describe('C/C++ source scope independent of broken AST parents', () => {
  it('requires a closing boundary before treating a macro-opened scope as executable', () => {
    const source = 'void generated() {\nCLOSE_BODY\nconst int actual_global = 1;';
    const scope = new CCppSourceScope(source);
    expect(scope.isExecutable(source.indexOf('actual_global'))).toBe(false);
    expect(scope.maskExecutableBodies(source)).toBe(source);
  });

  it('masks complete auxiliary bodies while preserving declarations, braces and coordinates', () => {
    const source = 'struct Owner { void run(); };\r\nvoid Owner::run() {\r\n  CALL_TOKEN(int, ->);\r\n}\r\nint after;';
    const masked = new CCppSourceScope(source).maskExecutableBodies(source);
    expect(masked).toHaveLength(source.length);
    expect(masked.split('\n').map(line => line.length)).toEqual(source.split('\n').map(line => line.length));
    expect(masked).toContain('struct Owner { void run(); }');
    expect(masked).toContain('void Owner::run() {');
    expect(masked).not.toContain('CALL_TOKEN');
    expect(masked).toContain('int after;');
  });

  it.each(['\n','\r\n'])('keeps branch alternatives and continued directives separate (%j)', newline => {
    const source = [
      'namespace demo {',
      '#define WRAP(x) \\',
      '  do { int macro_local; } while (0)',
      'void f() {',
      '#if FEATURE',
      '  if (true) {',
      '#else',
      '  if (false) {',
      '#endif',
      '    int actual_local;',
      '  }',
      '}',
      'int actual_global;',
      '}',
    ].join(newline);
    const scope = new CCppSourceScope(source);
    expect(scope.isDirective(source.indexOf('macro_local'))).toBe(true);
    expect(scope.isExecutable(source.indexOf('actual_local'))).toBe(true);
    expect(scope.isExecutable(source.indexOf('actual_global'))).toBe(false);
    const nodes = cpp(source).nodes;
    expect(nodes.some(n => n.name === 'actual_local' || n.name === 'macro_local')).toBe(false);
    expect(nodes).toContainEqual(expect.objectContaining({name:'actual_global', qualifiedName:'demo::actual_global'}));
  });

  it('does not treat data initializers, raw strings or type templates as function bodies', () => {
    const source = `template<class T> struct alignas(16) Holder { static const int member = 1; };
const char *text = R"tag( } void fake() { )tag";
int values[sizeof(int)] = {1, 2};
void run() { auto value = 1'000; int local_only; }
int global_after;`;
    const scope = new CCppSourceScope(source);
    expect(scope.isExecutable(source.indexOf('member'))).toBe(false);
    expect(scope.isExecutable(source.indexOf('local_only'))).toBe(true);
    expect(scope.isExecutable(source.indexOf('global_after'))).toBe(false);
    expect(cpp(source).nodes.some(n => n.name === 'local_only')).toBe(false);
  });

  it('recognizes lambda bodies while preserving the global variable owning the lambda', () => {
    const source = 'auto callback = [] { int lambda_local = 0; return lambda_local; };\nint after;';
    const scope = new CCppSourceScope(source);
    expect(scope.isExecutable(source.indexOf('lambda_local'))).toBe(true);
    expect(scope.isExecutable(source.indexOf('callback'))).toBe(false);
    expect(scope.isExecutable(source.indexOf('after'))).toBe(false);
  });
});
